apiVersion: 1

datasources:
  - name: "Cinnamon Tempo (via OpenTelemetry)"
    type: tempo
    url: http://tempo:3200
    access: proxy
    isDefault: false
    uid: cinnamon-tempo
    jsonData:
      serviceMap:
        datasourceUid: cinnamon-prometheus
