apiVersion: 1

datasources:
  - name: "Cinnamon Prometheus (via OpenTelemetry)"
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    uid: cinnamon-prometheus
